// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_trial.Data;

#nullable disable

namespace mvc_trial.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mvc_trial.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "this is category 1",
                            name = "category 1"
                        },
                        new
                        {
                            id = 2,
                            description = "this is category 2",
                            name = "category 2"
                        },
                        new
                        {
                            id = 3,
                            description = "this is category 3",
                            name = "category 3"
                        },
                        new
                        {
                            id = 4,
                            description = "this is category 4",
                            name = "category 4"
                        },
                        new
                        {
                            id = 5,
                            description = "this is category 5",
                            name = "category 5"
                        },
                        new
                        {
                            id = 6,
                            description = "this is category 6",
                            name = "category 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
